# Generated by Django 5.1.3 on 2024-11-09 22:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('count', models.PositiveIntegerField(default=1)),
                ('url_shortener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='app.urlshortener')),
            ],
            options={
                'unique_together': {('url_shortener', 'date')},
            },
        ),
    ]
